/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package lab;

/**
 *
 * @author Andy
 */
public class HomeWindow extends javax.swing.JFrame {

    /**
     * Creates new form HomeWindow
     */
    
    private final String CONVERT_FIRST = "Error: You must convert first.";
    private final String ERROR_MESSAGE = "Error: Please only enter a numeric value.";
    public HomeWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtF = new javax.swing.JTextField();
        lblSolution = new javax.swing.JLabel();
        btnC = new javax.swing.JButton();
        btnF = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Fahrenheit:");

        lblSolution.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSolution.setText("Celsius: ");

        btnC.setText("Convert");
        btnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCActionPerformed(evt);
            }
        });

        btnF.setText("Revert");
        btnF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtF, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(btnC)
                        .addGap(18, 18, 18)
                        .addComponent(btnF, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(lblSolution)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblSolution)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnC)
                    .addComponent(btnF))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCActionPerformed
        
        //Formula: (°F  -  32)  x  5/9 = °C
        if(txtF.getText() == null || txtF.getText().isEmpty()){
            lblSolution.setText(ERROR_MESSAGE);
        }else{
            double tempF = Double.parseDouble(txtF.getText());
            double tempC = Math.round((tempF-32.0)*(5.0/9.0));
            String answer = "Celsius: " + tempC;
            lblSolution.setText(answer);
        }
    }//GEN-LAST:event_btnCActionPerformed

    private void btnFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFActionPerformed
        
        if(lblSolution.getText().equals("Celsius: ") || lblSolution.getText().equals(CONVERT_FIRST)){
            lblSolution.setText(CONVERT_FIRST);
        }else if(lblSolution.getText().equals(CONVERT_FIRST) || lblSolution.getText().equals(ERROR_MESSAGE)){
            lblSolution.setText(CONVERT_FIRST);
        }else{
            String[] converted = lblSolution.getText().split(" ");
            double tempC = Double.parseDouble(converted[1]);
            double tempF = (9.0/5.0)*tempC + 32.0;
            String answer = "Fahrenheit: " + tempF;
            lblSolution.setText(answer);
        }
    }//GEN-LAST:event_btnFActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnC;
    private javax.swing.JButton btnF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblSolution;
    private javax.swing.JTextField txtF;
    // End of variables declaration//GEN-END:variables
}
